## This is the configuration file for the job system.
## This will only be enabled when the config flag LOAD_JOBS_FROM_TXT is enabled.
## We use a system of keys here that directly correlate to the job, just to ensure they don't desync if we choose to change the name of a job.
## You are able to change (as of now) five different variables in this file.
## Total Positions are how many job slots you get in a shift, Spawn Positions are how many you get that load in at spawn. If you set this to -1, it is unrestricted.
## Playtime Requirements is in minutes, and the job will unlock when a player reaches that amount of time.
## However, that can be superseded by Required Account Age, which is a time in days that you need to have had an account on the server for.
## Also there is a required character age in years. It prevents player from joining as this job, if their character's age as is lower than required. Setting it to 0 means it is turned off for this job.

## As time goes on, more config options may be added to this file.
## You can use the admin verb 'Generate Job Configuration' in-game to auto-regenerate this config as a downloadable file without having to manually edit this file if we add more jobs or more things you can edit here.
## It will always respect prior-existing values in the config, but will appropriately add more fields when they generate.
## It's strongly advised you create your own version of this file rather than use the one provisioned on the codebase.

## The game will not read any line that is commented out with a '#', as to allow you to defer to codebase defaults.
## If you want to override the codebase values, add the value and then uncomment that line by removing the # from the job key's name.
## Ensure that the key is flush, do not introduce any whitespaces when you uncomment a key. For example:
## "# Total Positions" should always be changed to "Total Positions", no additional spacing.
## Best of luck editing!

[GAKSTER]
"Playtime Requirements" = 0
"Required Account Age" = 0
"# Required Character Age" = 0
"Spawn Positions" = -1
"Total Positions" = -1

[FILTRE]
"Playtime Requirements" = 0
"Required Account Age" = 0
"# Required Character Age" = 0
"Spawn Positions" = 3
"Total Positions" = 0

[PINATA]
"Playtime Requirements" = 0
"Required Account Age" = 0
"# Required Character Age" = 0
"Spawn Positions" = 1
"Total Positions" = 0
